/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import IDTrackerTO.MembershipTO;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author tezk
 */
public class MembershipUtility {

    public static MembershipTO getAsTO(Membership aMembership) {
        MembershipTO newMembership = new MembershipTO();
        if (aMembership == null) {
            return newMembership;
        }

        newMembership.setId(aMembership.getId());
       // newMembership.getCustomerCollection().addAll(aMembership.getCustomerCollection());
        newMembership.setCaravanCollection(CaravanUtility.getAsTO(aMembership.getCaravanCollection()));
        newMembership.setDistrict(aMembership.getDistrict());
        newMembership.setElectricityHookup(aMembership.getElectricityHookup());
        newMembership.setElectricitychargeCollection(ElectricitychargeUtility.getAsTO(aMembership.getElectricitychargeCollection()));
        newMembership.setJoinedDate(aMembership.getJoinedDate());
        newMembership.setLockerId(aMembership.getLockerId());
        newMembership.setMembershipNo(aMembership.getMembershipNo());
        newMembership.setMembershipchargeCollection(MembershipchargeUtility.getAsTO(aMembership.getMembershipchargeCollection()));
        newMembership.setParkingSpace(aMembership.getParkingSpace());
        newMembership.setPlotId(aMembership.getPlotId());
        newMembership.setSociety(aMembership.getSociety());
        newMembership.setSwipeCardId(aMembership.getSwipeCardId());
        newMembership.setType(aMembership.getType());
        newMembership.setWinterStorage(aMembership.getWinterStorage());
        newMembership.setInsuranceExpiry(aMembership.getInsuranceExpiry());

        return newMembership;
    }

    public static Membership getAsEntity(MembershipTO aMembership) {
        Membership newMembership = new Membership();
        if (aMembership == null) {
            return newMembership;
        }
        // Membership PK is same as Customers - not autogenerated
        newMembership.setId(aMembership.getId());
        //newMembership.setCustomer(aMembership.getCustomer().getId());
        newMembership.setCaravanCollection(CaravanUtility.getAsEntity(aMembership.getCaravanCollection()));
        newMembership.setDistrict(aMembership.getDistrict());
        newMembership.setElectricityHookup(aMembership.getElectricityHookup());
        newMembership.setElectricitychargeCollection(ElectricitychargeUtility.getAsEntity(aMembership.getElectricitychargeCollection()));
        newMembership.setJoinedDate(aMembership.getJoinedDate());
        newMembership.setLockerId(aMembership.getLockerId());
        newMembership.setMembershipNo(aMembership.getMembershipNo());
        newMembership.setMembershipchargeCollection(MembershipchargeUtility.getAsEntity(aMembership.getMembershipchargeCollection()));
        newMembership.setParkingSpace(aMembership.getParkingSpace());
        newMembership.setPlotId(aMembership.getPlotId());
        newMembership.setSociety(aMembership.getSociety());
        newMembership.setSwipeCardId(aMembership.getSwipeCardId());
        newMembership.setType(aMembership.getType());
        newMembership.setWinterStorage(aMembership.getWinterStorage());
        newMembership.setInsuranceExpiry(aMembership.getInsuranceExpiry());

        return newMembership;

    }

    public static Collection<MembershipTO> getAsTO(Collection<Membership> members) {
        Collection<MembershipTO> newMembers = new ArrayList();

        for (Membership eachMember : members) {
            newMembers.add(getAsTO(eachMember));
        }
        return newMembers;
    }

    public static Collection<Membership> getAsEntity(Collection<MembershipTO> members) {
        Collection<Membership> newMembers = new ArrayList();

        for (MembershipTO eachMember : members) {
            newMembers.add(getAsEntity(eachMember));
        }
        return newMembers;
    }
}
